// Generated by CoffeeScript 1.6.3
(function() {
  var fs, tbl;

  fs = require('fs');

  tbl = require('./lib/tbls');

  Handlebars.registerHelper('lowerCase', function(x) {
    return x.toLowerCase();
  });

  Handlebars.registerHelper('join', function(context, options) {
    var data, i, j, result, s, sep, _i, _ref;
    result = [];
    sep = options.hash['sep'] || ',';
    s = options.hash['start'] ^ 0;
    data = null;
    j = context.length;
    for (i = _i = s, _ref = j - 1; s <= _ref ? _i <= _ref : _i >= _ref; i = s <= _ref ? ++_i : --_i) {
      if (options.data) {
        data = Handlebars.createFrame(options.data || {});
        data.index = i;
        if (i === j - 1) {
          data.last = true;
        } else {
          data.last = false;
        }
      }
      result.push(options.fn(context[i], {
        data: data
      }));
    }
    return result.join(sep);
  });

  $(function() {
    var $tpls, $txtClass, $txtFFields, $txtFields, $txtPkg, $txtQFields, compilers, cp, dir, get_list, onBtnCreateHandler, onBtnDlClick, onBtnTargetClick, onTargetChange, sources, tpls, tplsCompiler;
    dir = localStorage.path;
    if (dir) {
      $('#target').html(dir);
    }
    tpls = [['EntityController.java', '{{package}}.controller.{{class}}Controller.java'], ['IEntityService.java', '{{package}}.service.I{{class}}Service.java'], ['EntityService.java', '{{package}}.service.impl.{{class}}ServiceImpl.java'], ['IEntityMapper.java', '{{package}}.persistence.I{{class}}Mapper.java'], ['EntityMapper.xml', '{{package}}.persistence.mapper.{{class}}Mapper.xml']];
    compilers = [];
    $txtClass = $('#txtClass');
    $txtPkg = $('#txtPkg');
    $txtFields = $('#txtFields');
    $txtFFields = $('#txtFFields');
    $txtQFields = $('#txtQFields');
    $tpls = $('#entry-template');
    tplsCompiler = Handlebars.compile($tpls.html());
    sources = null;
    cp = function(tpl) {
      var name_compiler, source_compiler, source_tpl;
      source_tpl = fs.readFileSync('tpls/' + tpl[0] + '.tpl', 'utf8');
      source_compiler = Handlebars.compile(source_tpl);
      name_compiler = Handlebars.compile(tpl[1]);
      return compilers.push({
        source: source_compiler,
        name: name_compiler
      });
    };
    _.each(tpls, cp);
    get_list = function($, sep) {
      var val;
      val = $.val().trim();
      if (val === '') {
        return false;
      }
      return val.split(sep || ',');
    };
    onBtnCreateHandler = function(event) {
      var html,
        _this = this;
      sources = [];
      _.each(compilers, function(compiler) {
        var context, fFields, fields, klass, name, name_compiler, pkg, qFields, source, source_compiler;
        source_compiler = compiler.source;
        name_compiler = compiler.name;
        pkg = $txtPkg.val();
        klass = $txtClass.val();
        fields = get_list($txtFields);
        fFields = get_list($txtFFields);
        qFields = get_list($txtQFields);
        context = {
          'package': pkg,
          'class': klass,
          'fields': fields,
          'fFields': fFields,
          'qFields': qFields
        };
        name = name_compiler(context);
        source = source_compiler(context);
        return sources.push({
          title: name,
          content: source
        });
      });
      html = tplsCompiler({
        sources: sources
      });
      $('#content').empty().html(html);
      $('.java').each(function(i, e) {
        return hljs.highlightBlock(e);
      });
      return $('#btnDl').removeAttr('disabled').html('生成代码').css('color', 'black');
    };
    onTargetChange = function() {
      localStorage.path = this.value;
      return $('#target').html(this.value);
    };
    onBtnTargetClick = function() {
      return $('#targetDir').click();
    };
    onBtnDlClick = function() {
      var _this = this;
      _.each(sources, function(source) {
        var content, file;
        file = source.title;
        content = source.content;
        return tbl.save(localStorage.path.split('/').join('.') + '/' + file, _.unescape(content));
      });
      return $('#btnDl').html('代码已生成！').attr('disabled', true).css('color', 'red');
    };
    $('#btnCreate').click(onBtnCreateHandler);
    $('#targetDir').change(onTargetChange);
    $('#btnTarget').click(onBtnTargetClick);
    return $('#btnDl').click(onBtnDlClick);
  });

}).call(this);

/*
//@ sourceMappingURL=init.map
*/
